spring:
  application:
    name: jm_dms
  main:
    allow-circular-references: true
    
config:
  paymentModes: CASH, UPI, CREDIT, CARD(CREDIT), CARD(DEBIT), BANK TRANSFER
  leaveType: SICK, CASUAL, EARNED, UNPAID